/*
 * Generated by zmk/tools/cat_frames.py; edit the art there and run it again.
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include <lvgl.h>

/** Size of every cat frame as it appears on the status screen, upright. */
#define CAT_WIDTH 22
#define CAT_HEIGHT 16

enum cat_frame {
    CAT_WALK_0,
    CAT_WALK_1,
    CAT_WALK_2,
    CAT_WALK_3,
    CAT_SIT,
    CAT_BLINK,
    CAT_SLEEP_0,
    CAT_SLEEP_1,
    CAT_FRAME_COUNT,
};

/** Every frame, rotated for the status screen: CAT_HEIGHT wide, CAT_WIDTH tall. */
extern const lv_image_dsc_t *const cat_frames[CAT_FRAME_COUNT];
